### ISSUE TITLE
DBのスキーマをリポジトリに含める

### ISSUE THREAD

**Issue by ms2sato** [rinkun/kami-e.fan#1]
他の人とやりとりするときにはDBのスキーマを共有すると便利です。
例えば今私が @rinkun さんのシステムを動かそうとすると、DBの内容がわからないために結構な時間がかかります。phpMyAdminからsql形式でDBのcreate文などをエクスポートする機能があるので調べてみてください。

**Comment by papagram** [comment]
DBのダンプファイルをメールに添付しました。
ご確認下さい。

**Comment by ms2sato** [comment]
:+1: オッケーです！
