### ISSUE TITLE
ファイルアップロードができない

### ISSUE THREAD

**Issue by ms2sato** [rinkun/kami-e.fan#3]
ファイルのアップロードが放置されているとのことですが
どういったことができていて、何ができていないかを教えてください。
また、もしもエラーが発生している場合にはエラーメッセージなども手がかりになります。

**Comment by papagram** [comment]
imageのアップロードは時間切れで作業途中という意味です。
一度作ったことがありますので、アップロードのコードは書けると思います。
やってみます。

**Comment by papagram** [comment]
アップロードされたimageファイルをバリデーションし、ディレクトリに保存、サムネイル作成・保存、imgタグで表示のコードを作りました。

**Comment by ms2sato** [comment]
確認しました！大丈夫そうですね。
