### ISSUE TITLE
Viewの共通部をヘッダ、フッタとして切り分けて外部ファイルとする

### ISSUE THREAD

**Issue by ms2sato** [rinkun/kami-e.fan#5]

**Comment by papagram** [comment]
Viewのheadタグ、ヘッダー、フッターを外部ファイル化しました。
common_htmlディレクトリ下に、
head.php　：　headタグの部分
header.php　：　ナビゲーションの部分
footer.php　：　コピーライトの部分
3つのファイルを作成しました。

**Comment by ms2sato** [comment]
まずは良いと思います。今後何かあったらまた考えましょう。
